Core initial implementation
Gepardec/CheetUnit pull request #9
Opened 2020-11-20 13:18 UTC by eerofeev

2020-11-20 13:31 UTC, patholzer commented on cheetunit-core/src/main/java/com/gepardec/cheetunit/core/CheetUnitExecuter.java
> +public class CheetUnitExecuter {
better rename to CheetUnitExecutor

2020-11-20 13:34 UTC, patholzer commented on cheetunit-core/src/main/java/com/gepardec/cheetunit/core/CheetUnitClassloader.java
> +    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
JavaDoc would be appreciated here, as we already had a clearifing discussion for this method

2020-11-20 13:43 UTC, patholzer requested changes

2020-11-20 13:43 UTC, patholzer commented on cheetunit-test/src/main/java/com/gepardec/cheetunit/test/RequestDTOFactory.java
>  class RequestDTOFactory {
Rename to ExecutionRequestFactory

2020-11-20 13:43 UTC, patholzer commented on cheetunit-test/pom.xml
> +            <artifactId>cheetunit-wildfly</artifactId>
use cheetunit-core instead of cheetunit-wildfly

2020-11-26 07:28 UTC, csalmhof approved these changes

2020-11-26 09:15 UTC, patholzer approved these changes

2020-11-26 12:07 UTC, merged